/**
 * API
 * Oauth2-secured API
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonsDetailsDTO { 
    username?: string;
    phoneNumber?: string;
    email?: string;
    picture?: Array<string>;
}

